# Les graphe

In [30]:
import numpy as np

In [31]:
#matrice adjascente pour graphe non oriente
#ex2
def MatAdj(S,A):
    matrice=np.zeros((len(S),len(S)))
    for i in A:
        a,b=i
        matrice[a][b]=1
        matrice[b][a]=1
    return matrice

In [32]:
S=[0,1,2,3,4,5,6]
A=[(0,1),(0,2),(1,2),(1,5),(2,3),(2,4),(3,6),(4,6),(5,6)]
MatAdj(S,A)

array([[0., 1., 1., 0., 0., 0., 0.],
       [1., 0., 1., 0., 0., 1., 0.],
       [1., 1., 0., 1., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 1., 1., 0.]])

In [33]:
M=MatAdj(S,A)
M[2]

array([1., 1., 0., 1., 1., 0., 0.])

In [24]:
#matrice adjascente pour graphe oriente avec des cout
def MatAdjOrient(S,A):
        matrice=np.full((len(S), len(S)), np.inf)
        for i in range(len(S)):
                matrice[i][i]=0
        for i in A:
                a,b,c=i
                matrice[a][b]=c
        return matrice    

In [25]:
S=[0,1,2,3,4,5,6]
A=[(0,1,3),(0,2,12),(1,3,5),(1,5,35),(2,3,9),(2,4,15),(3,5,8),(3,4,10),(5,6,13),(4,6,14)]
# A=[(0,1,3),(0,2,10),(1,2,4),(1,5,12),(2,3,1),(2,4,7),(3,6,9),(4,6,16),(5,6,11)]
MatAdjOrient(S,A)

array([[ 0.,  3., 12., inf, inf, inf, inf],
       [inf,  0., inf,  5., inf, 35., inf],
       [inf, inf,  0.,  9., 15., inf, inf],
       [inf, inf, inf,  0., 10.,  8., inf],
       [inf, inf, inf, inf,  0., inf, 14.],
       [inf, inf, inf, inf, inf,  0., 13.],
       [inf, inf, inf, inf, inf, inf,  0.]])

In [65]:
#degre d'un sommet
def degre(s,M):
    count=0
    for i in M[s]:
        if i!=0:
            count=count+1
    return count

In [66]:
S=[0,1,2,3,4,5,6]
A=[(0,1),(0,2),(1,2),(1,5),(2,3),(2,4),(3,6),(4,6),(5,6)]
M=MatAdj(S,A)
degre(0,M)


2

In [9]:
def eulerien(S,M):
    for i in S:
        d=degre(i,M)
        if d==0 or d%2!=0:
            return False
    return True

In [10]:
M=MatAdj(S,A)
eulerien(S,M)

False

In [77]:
#ex3
#parcours en largeur
def successeursNonvisite(G,S,visite):
    voisins=[]
    for i in range(len(G[S])):
        if G[S][i]!=0 and i not in visite:
            voisins+=[i]
    return voisins

def successeur1(G,S):
    v = []
    for i in range(len(G[S])):
        if G[S][i]!=0:
            v.append(i)
    return v

def ParcourLargeur(G,depart):
    F=[depart]
    parcours=[]
    while len(F)!=0:
        S=F.pop(0)
        parcours.append(S)
        succ=successeursNonvisite(G,S,F+parcours)
        F.extend(succ)
    return parcours         

In [84]:
S=[0,1,2,3,4,5,6]
A=[(0,1),(0,2),(1,2),(1,5),(2,3),(2,4),(3,6),(4,6),(5,6)]
G=MatAdj(S,A)
print(G)
ParcourLargeur(G,3)
# successeur1(G,2)

[[0. 1. 1. 0. 0. 0. 0.]
 [1. 0. 1. 0. 0. 1. 0.]
 [1. 1. 0. 1. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 1. 1. 0.]]


[3, 2, 6, 0, 1, 4, 5]

In [82]:
#parcours en profondeur
def ParcoursProfondeur(G,depart):
    p=[depart]
    parcours=[]
    while len(p)!=0:
        S=p[-1]
        succ=successeursNonvisite(G,S,p+parcours)
        if len(succ)!=0:
            p.append(succ[0])
        else:
            parcours=[p.pop(-1)]+parcours #car il est un pile pour ne pas inverser a la fin
    return parcours

In [83]:
ParcoursProfondeur(G,3)

[3, 2, 0, 1, 5, 6, 4]

In [15]:
#djikestra
def IndiceMinDistance(D,NonMarque):
    InMin=NonMarque[0]
    for i in NonMarque[1:]:
        if D[i]<D[InMin]:
            InMin=i
    return InMin
def successurNonMarque(G,S,NonMarque):
    x=[]
    for i in NonMarque:
        if G[S][i]!=np.inf:
            x.append(i)
    return x

In [16]:
D=[3,12,8,0,np.inf,16,np.inf]
s=[1,4,5,6]
IndiceMinDistance(D,s)

1

In [17]:
# Exemple de matrice d'adjacence
G = np.array([
    [np.inf, 2, np.inf, 1],
    [np.inf, np.inf, 3, np.inf],
    [4, np.inf, np.inf, np.inf],
    [np.inf, np.inf, np.inf, np.inf]
])
sommet_S = 0
successurNonMarque(G, sommet_S, [0, 1, 2, 3])

[1, 3]

In [18]:
#Si un nœud A a une arête dirigée vers un nœud B, alors B est un successeur de A.
#Si un nœud B a une arête dirigée vers un nœud A, alors B est un prédécesseur de A.

In [19]:
def Dijkstra(G,dep,arr):
    n=len(G) #le nombre de sommets dans le graphe G
    D=[np.inf]*n #Initialise une liste D qui représente les distances minimales 
    #actuellement connues depuis le sommet de départ (dep).
    #Toutes les distances sont initialisées à l'infini, sauf la distance du sommet de départ à lui-même, qui est mise à zéro.
    D[dep]=0
    P=[dep]*n #Initialise une liste P qui stocke le prédécesseur de chaque sommet sur 
    #le chemin le plus court depuis le sommet de départ jusqu'à ce sommet.
    Nnmarque=list(range(n))#Initialise une liste Nnmarque contenant tous les sommets du graphe.
    #Au début,tous les sommets sont non marqués.
    while arr in Nnmarque: # Continue tant que le sommet d'arrivée arr n'est pas marqué.
        m=IndiceMinDistance(D,Nnmarque)#retourne l'indice du sommet ayant la plus petite distance dans la liste D.
        Nnmarque.remove(m) #marquer le sommet m 
        sv=successurNonMarque(G,m,Nnmarque)#Obtient la liste des successeurs non marqués du sommet m
        for k in sv: #examine chaque successeur non marqué
            if D[k]>D[m]+G[m][k]: #Vérifie si la distance actuelle à k est plus grande que 
                #la somme de la distance actuelle à m et du poids de l'arête de m à k.
                D[k]=D[m]+G[m][k]
                P[k]=m
    return D,P #les distances minimales  

In [20]:
G = np.array([
    [0,3,12,np.inf,np.inf,np.inf,np.inf],
    [np.inf,0,np.inf,5,np.inf,35,np.inf],
    [np.inf,np.inf,0,9,15,np.inf,np.inf],
    [np.inf,np.inf,np.inf,0,10,8,np.inf],
    [np.inf, np.inf, np.inf,np.inf,0,np.inf,14],
    [np.inf,np.inf,np.inf,np.inf,np.inf,0,13],
    [np.inf,np.inf,np.inf,np.inf,np.inf,np.inf,0]
])
depart = 0
arrivee = 6
resultats = Dijkstra(G, depart, arrivee)
print(resultats)

([0, 3.0, 12.0, 8.0, 18.0, 16.0, 29.0], [0, 0, 0, 1, 3, 3, 5])


In [21]:
#bellman Ford
def predesseur(G,S):
    l=[]
    for i in range(len(G[S])):
        if G[i][S]!=np.inf:
            l.append(i)
    return l

In [22]:
G=np.array([
[np.inf,4,np.inf,5],
[np.inf,np.inf,np.inf,np.inf],
[np.inf,-10,np.inf,np.inf],
[np.inf,np.inf,3,np.inf]])
predesseur(G,1)

[0, 2]

In [23]:
def predecesseur(G,S): #les colonnes représentent les predecesseurs et les lignes représentent les successeurs
    l=[]
    for i in range (len(G)):
        if G[i][S]!=np.inf:
            l.append(i)
    return l 


def bellman_ford(G,dep): # la matrice d'adjacence pondérée G et le sommet de départ dep
    n=len(G) #nbre de sommets
    D=np.zeros((n,n))+np.inf #toutes les distances  à l'infini
    #D[:,0]=0 toute les lignes de la colonne zero recoit zero
    D[:,dep]=0 # Initialise à zéro toutes les distances minimales de la colonne correspondant au sommet de départ
    P=[dep]*n # Initialise la liste P des prédécesseurs, avec tous les prédécesseurs initialisés au sommet de départ
    #le predesseceur choisi pour chaque sommet
    for lg in range (1,n): #Itération sur les lignes de la matrice D, à partir de la deuxième ligne.
        for s in range(n):  #Itération sur chaque sommet.
            Pr=predecesseur(G,s)  #liste des predecesseurs de s
            for p in Pr :#p est in predecesseur de s
                if D[lg-1,p]!=np.inf: #Vérifie si la distance minimale précédente pour le prédécesseur p est différente de l'infini.
                    if D[lg-1,p]+G[p,s]<D[lg-1,s]: #Vérifie si une nouvelle distance minimale est trouvée en passant par le prédécesseur p
                        D[lg:,s]=D[lg-1,p]+G[p,s]  #Met à jour les distances minimales à partir de la ligne actuelle.
                        P[s]=p #Met à jour le prédécesseur associé à s.
    #iteration de verification 
    for s in range(n): 
        pr=predecesseur(G,s)
        for p in pr : 
            if D[n-1,p]!=np.inf:
                if D[n-1,p]+G[p,s]<D[n-1,s]:
                    return "pas de solution , il existe un circuit absorbant !"
    return D[n-1],P

In [24]:
bellman_ford(G,0)

(array([ 0., -2.,  8.,  5.]), [0, 2, 3, 0])

In [25]:
#floyd_warshall
def Floyd_Warshall(G):
    D=G
    for k in range(len(G)):#intermediaire
        for i in range(len(G)):#ligne
            for j in range(len(G)):#colonne 
                if (i==j):
                    D[i][j]=0
                if G[i][k]+G[k][j]<G[i][j]:
                    D[i][j]=G[i][k]+G[k][j]
    return D

In [26]:
array=np.array([[np.inf,1,7,np.inf,np.inf,3],
[1,np.inf,1,np.inf,np.inf,1],
[7,1,np.inf,np.inf,np.inf,np.inf],
[np.inf,np.inf,np.inf,np.inf,2,2],
[np.inf,np.inf,np.inf,2,np.inf,5],
[3,1,np.inf,2,5,np.inf],])
Floyd_Warshall(array)

array([[0., 1., 2., 4., 6., 2.],
       [1., 0., 1., 3., 5., 1.],
       [2., 1., 0., 4., 6., 2.],
       [4., 3., 4., 0., 2., 2.],
       [6., 5., 6., 2., 0., 4.],
       [2., 1., 2., 2., 4., 0.]])

In [27]:
#td5
#1
def valeurMassique(objet):
    l=[]
    for i in objet.items():
        valMassiq=i[1][1]/i[1][0]
        l.append((round(valMassiq),i[1][0],i[1][1],i[0]))
#     l.sort(reverse=True)
    return l

In [28]:
objet={'A':(13,700),'C':(8,300),'B':(12,400),'D':(10,300)}
valeurMassique(objet)

[(54, 13, 700, 'A'), (38, 8, 300, 'C'), (33, 12, 400, 'B'), (30, 10, 300, 'D')]

In [29]:
def SacADos(objet, poids):
    som = 0
    l = []
    valeurEuro=0
    for i in objet.items():
        som = som + i[1][0]
        if som <= poids:
            valeurEuro+=i[1][1]
            l.append(i[0])
        else:
            break  # Sortir de la boucle si le poids maximal est dépassé
    return (l,'Avec un cout de',valeurEuro,'Euros')

In [30]:
objet={'A':(13,700),'C':(8,300),'B':(12,400),'D':(10,300)}
SacADos(objet,30)

(['A', 'C'], 'Avec un cout de', 1000, 'Euros')

In [13]:
def rendu(L,N):
    rendu_monnaie=[]
    somme=0
    index=0
    while somme!=N and index<len(L):
        if somme+L[index]<=N:
            rendu_monnaie.append(L[index])
            somme+=L[index]
        else:
            index+=1
    if somme==N:
        return rendu_monnaie
    else:
        return ('pas de solution,rendu optimal egal a ',rendu_monnaie,'de somme egal a somme ',sum(rendu_monnaie))

In [14]:
print(rendu([30, 24, 12, 6, 3, 1], 49))
print(rendu([25, 10, 5, 1], 87))
print(rendu([31, 22, 10, 2], 100))

[30, 12, 6, 1]
[25, 25, 25, 10, 1, 1]
('pas de solution,rendu optimal egal a ', [31, 31, 31, 2, 2, 2], 'de somme egal a somme ', 99)


In [15]:
def rendu_monnaie(L,N):
    list_monnaie=[]
    reste=N
    #verifier si tous les elements de la list est infirieur a N
    #etape supplimetaire
    for i in L:
        while i<=reste:
            list_monnaie.append(i)
            reste=reste-i
        if reste==0:
                break
    if reste==0:
        return list_monnaie
    else:
        return ('pas de solution,rendu optimal egal a ',list_monnaie,'de somme egal a somme ',sum(list_monnaie))
print(rendu_monnaie([30, 24, 12, 6, 3, 1], 49))
print(rendu_monnaie([25, 10, 5, 1], 87))
print(rendu_monnaie([31, 22, 10, 2], 100))

[30, 12, 6, 1]
[25, 25, 25, 10, 1, 1]
('pas de solution,rendu optimal egal a ', [31, 31, 31, 2, 2, 2], 'de somme egal a somme ', 99)


In [16]:
#2
def rendu_monnaie(L,N):
    list_monnaie=[]
    som=0
    list_initial=[]
    #verifier si tous les elements de la list est infirieur a N
    #etape supplimetaire
    for i in L:
        if i<=N:
            list_initial.append(i)
    
    for i in range(len(list_initial)):
        som+=list_initial[i]
        if som<=N:
            list_monnaie.append(list_initial[i])
        else:
            som-=list_initial[i]
    if som==N:
        return list_monnaie
    else:
        return ('pas de solution,rendu optimal egal a ',list_monnaie,'de somme egal a somme ',sum(list_monnaie))

print(rendu_monnaie([30, 24, 12, 6, 3, 1], 49))
print(rendu_monnaie([25, 10, 5, 1], 87))
print(rendu_monnaie([31, 22, 10, 2], 100))

[30, 12, 6, 1]
('pas de solution,rendu optimal egal a ', [25, 10, 5, 1], 'de somme egal a somme ', 41)
('pas de solution,rendu optimal egal a ', [31, 22, 10, 2], 'de somme egal a somme ', 65)


In [32]:
#location de voiture
def tri(d,f,n):
    for i in range(len(f)):
        for j in range(i+1,len(f)):#pour comparer avec tous les elements restees
            if f[j]<f[i]:
                f[i], f[j] = f[j], f[i]
                d[i], d[j] = d[j], d[i]
                n[i], n[j] = n[j], n[i]
    return n,d,f

In [33]:
n=[0,1,2,3,4,5,6,7,8]
d=[1,2,4,1,5,8,9,13,11]
f=[8,5,7,3,9,11,10,16,14]
a,b,c=tri(d,f,n)
print(a)
print(b)
print(c)

[3, 1, 2, 0, 4, 6, 5, 8, 7]
[1, 2, 4, 1, 5, 9, 8, 11, 13]
[3, 5, 7, 8, 9, 10, 11, 14, 16]


In [34]:
def location(d,f,n):
    n,d,f=tri(d,f,n)
    result = [n[0]]  # La première demande est toujours incluse
    last_end_time = f[0]
    for i in range(1,len(f)):
        if d[i]>last_end_time:
            last_end_time=f[i]
            result.append(n[i])
            
    return result

In [35]:
n=[0,1,2,3,4,5,6,7,8]
d=[1,2,4,1,5,8,9,13,11]
f=[8,5,7,3,9,11,10,16,14]
l=location(d,f,n)
print(l)

[3, 2, 6, 8]


In [51]:
#empaquetage
def empaquetage(p,c):
    p.sort(reverse=True)
    boites=[]
    for poids in p:
        placed=False
        for boite in boites:
            if sum(boite)+poids<=c:
                boite.append(poids)
                placed=True
                break
        if not placed:
             boites.append([poids])#dans la premiere iteration on va executer ca   
    return boites

In [52]:
p=[7, 6, 3, 4, 8, 5, 9, 2]
c= 11
empaquetage(p,c)

[[9, 2], [8, 3], [7, 4], [6, 5]]

In [26]:
def prefixe(M,S):
    for i in range(len(S)):
        if M==S[:i]:
            return True
    else:
        return False

In [27]:
def prefix(M,S):
    m=len(M)
    return M==S[:m]

In [29]:
S = "SALADE"
M = "SAL"
prefix(M,S)

True

In [32]:
def suf(S):
    l = []
    for i in range(len(S)):
        l.append((S[i:],i))
    return l

In [37]:
def suffixe1(S):
    return [(i,S[i:]) for i in range(len(S))]

In [43]:
S = "TATCTAGCTA"
suf(S)

[('TATCTAGCTA', 0),
 ('ATCTAGCTA', 1),
 ('TCTAGCTA', 2),
 ('CTAGCTA', 3),
 ('TAGCTA', 4),
 ('AGCTA', 5),
 ('GCTA', 6),
 ('CTA', 7),
 ('TA', 8),
 ('A', 9)]

In [41]:
def fusion(P,Q):
    if P==[] or Q==[] : return P+Q
    elif P[0][0]<Q[0][0] : return [P[0]]+fusion(P[1:],Q)
    else: return [Q[0]]+fusion(P,Q[1:])

def tri11(F):
    n = len(F)
    if n<=1 : return F
    return fusion(tri(F[:n//2]),tri(F[n//2:]))

In [44]:
tri11(suf(S))

[('A', 9),
 ('AGCTA', 5),
 ('ATCTAGCTA', 1),
 ('CTA', 7),
 ('CTAGCTA', 3),
 ('GCTA', 6),
 ('TA', 8),
 ('TAGCTA', 4),
 ('TATCTAGCTA', 0),
 ('TCTAGCTA', 2)]

In [46]:
def feuilles(R):
    if (R[1]==[]): 
        return [R[0]]
    L=[]
    for f in R[1]:
        L = L + feuilles(f)
    return L

L1 = [ '#', [ [ 'A', [ [ 9, [ ] ], [ 'GCTA', [ [ 5,[ ] ] ] ], [ 'TCTAGCTA', [ [ 1, [ ] ] ] ] ] ], [ 'CTA',[ [ 7, [ ] ], [ 'GCTA', [ [ 3, [ ] ] ] ] ] ], [ 'GCTA', [ [ 6, [ ] ] ] ], [ 'T', [ [ 'A', [ [ 8, [ ] ], [ 'GCTA', [ [ 4, [ ] ] ] ], [ 'TCTAGCTA', [ [ 0, [ ] ] ] ] ] ], [ 'CTAGCTA', [ [ 2, [ ] ] ] ] ] ] ] ]
feuilles(L1)

[9, 5, 1, 7, 3, 6, 8, 4, 0, 2]

In [52]:
def recherche_arbre(M,R):
    for f in R[1]:
        if f[1]!=[]:
            if prefix(M,f[0]):
                return feuilles(f)
            elif prefix(f[0],M):
                n=len(f[0])
                return recherche_arbre(M[n:],f)
    return []

M = 'A'
L1 = [ '#', [ [ 'A', [ [ 9, [ ] ], [ 'GCTA', [ [ 5,[ ] ] ] ], [ 'TCTAGCTA', [ [ 1, [ ] ] ] ] ] ], [ 'CTA',[ [ 7, [ ] ], [ 'GCTA', [ [ 3, [ ] ] ] ] ] ], [ 'GCTA', [ [ 6, [ ] ] ] ], [ 'T', [ [ 'A', [ [ 8, [ ] ], [ 'GCTA', [ [ 4, [ ] ] ] ], [ 'TCTAGCTA', [ [ 0, [ ] ] ] ] ] ], [ 'CTAGCTA', [ [ 2, [ ] ] ] ] ] ] ] ]
recherche_arbre(M,L1)

[9, 5, 1]

In [53]:
def matrice(P,Q):
    a,b=len(P),len(Q)
    # M=[[0]*b for i in range(a)]
    M = [[0 for j in range(b)] for i in range(a)]
    for i in range(a):
        for j in range(b):
            if P[i]==Q[j]:
                M[i][j]=M[i-1][j-1]+1
    return M

P = 'GCTAGCATT'
Q = 'CATTGTAGCT'
m = matrice(P,Q)
print("La metrice: ")
print(m)

La metrice: 
[[0, 0, 0, 0, 1, 0, 0, 1, 0, 0], [1, 0, 0, 0, 0, 0, 0, 0, 2, 0], [0, 0, 1, 1, 0, 1, 0, 0, 0, 3], [0, 1, 0, 0, 0, 0, 2, 0, 0, 0], [0, 0, 0, 0, 1, 0, 0, 3, 0, 0], [1, 0, 0, 0, 0, 0, 0, 0, 4, 0], [0, 2, 0, 0, 0, 0, 1, 0, 0, 0], [0, 0, 3, 1, 0, 1, 0, 0, 0, 1], [0, 0, 1, 4, 0, 1, 0, 0, 0, 1]]
